# TGC Faculty App — Shopify Configuration

name = "TGC Faculty"
client_id = "8cea6c356df78fb8940a328ef6b6abad"

[access_scopes]
scopes = "write_metaobjects,read_metaobjects,write_products,read_products,write_collections,read_collections,write_metafields,read_metafields,write_files,read_files"

[app_proxy]
url = "/proxy"
subpath = "faculty"
prefix = "apps"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "krjpjc-cy.myshopify.com"
